### ISSUE TITLE
기능 개선 및 예외 처리

### ISSUE THREAD

**Issue by Starlight258** [Step3-kakao-tech-campus/Team10_BE#180]
## Tasks
- [x] 구현된 기능에서 놓친 부분 반영
- [x] API 문서에 테스트케이스 반영
- [x] 프론트 요구사항 반영
