### ISSUE TITLE
사장님 관리 기능 구현

### ISSUE THREAD

**Issue by Starlight258** [Step3-kakao-tech-campus/Team10_BE#29]
## Tasks
- [x] 매장 관리 - owner별
- [x] 매출 관리 
- [x] 총 매출 금액 조회
- [x] 매장 관리 - 세차장별
- [x] 사장님 홈
