### ISSUE TITLE
사진 첨부 파일 업로드 및 조회 기능 구현

### ISSUE THREAD

**Issue by Starlight258** [Step3-kakao-tech-campus/Team10_BE#32]
## Tasks
- [ ] 사진 업로드할 서버 구성
- [ ] 사진 업로드 기능
- [ ] 사진 조회 기능

### 반영될 코드 (사진이 사용되는 부분)
- 세차장 등록 기능
- 예약 조회 기능
- 주변 세차장 조회 기능(지도)
