### ISSUE TITLE
세차장 등록 기능 구현

### ISSUE THREAD

**Issue by Starlight258** [Step3-kakao-tech-campus/Team10_BE#5]
## Tasks
- [x] 세차장, 베이, 운영시간, 지역, 키워드 entity 만들기
- [x] 등록 기능 만들기
- [x] 테스트 작성 및 검증
