### ISSUE TITLE
세차장 위치기반 검색 기능 구현

### ISSUE THREAD

**Issue by Cheoroo** [Step3-kakao-tech-campus/Team10_BE#57]
사용자가 키워드와 위치를 기반으로 세차장을 검색할 수 있는 기능 구현.

## Tasks
- [x] 키워드 기반 검색 로직 구현
- [x] 위치 정보를 사용한 검색 필터링 로직 구현.
- [x] 검색 결과 정렬 로직 구현 (예: 거리 기준).
- [x] 거리 계산 기능 구현
- [ ] 테스트 코드 작성

**Comment by Cheoroo** [comment]
성공 테스트만 작성했는데 실패 테스트도 금요일에 작성 할수 있으면 작성 하겠습니다!!~

**Comment by Cheoroo** [comment]
리뷰 반영 하여 쿼리로 검색 받게끔 개선했습니다
